namespace Kostic017.Pigeon
{
    public enum CodeErrorType
    {
        ILLEGAL_NUMBER,
        EXPECTED_TOKEN,
        UNTERMINATED_STRING,
        INVALID_ESCAPE_CHAR,
        UNEXPECTED_CHARACTER,
        INVALID_EXPRESSION_TERM,
        UNTERMINATED_COMMENT_BLOCK,
        UNTERMINATED_STATEMENT_BLOCK,
        EXPECTED_STATEMENT,
    }
}
